# 高性能配置 - 深度伪造检测系统
# 充分利用RTX4070 Laptop性能的配置

# 数据配置
data:
  data_dir: "./data"  # 数据目录
  max_videos_per_class: 1000  # 每类最大视频数
  max_frames: 64  # 每个视频最大帧数（更多帧获得更好效果）
  frame_size: [256, 256]  # 更高分辨率
  train_split: 0.8  # 更多训练数据
  val_split: 0.15
  test_split: 0.05
  
  # 数据预处理
  quality_threshold: 60  # 更高质量阈值
  skip_frames: 1  # 不跳帧，使用所有帧
  use_gpu_preprocessing: true  # GPU加速预处理
  
# 模型配置
model:
  backbone: "resnet50"  # 使用ResNet50获得更好性能
  hidden_dim: 1024  # 更大的隐藏维度
  num_layers: 3    # 更多LSTM层
  dropout: 0.4     # 适中的Dropout
  use_attention: true  # 使用注意力机制
  attention_heads: 16  # 更多注意力头
  pretrained: true
  
  # 分类器配置
  classifier_layers: [1024, 512, 256, 1]  # 更深的分类器
  classifier_dropout: 0.3
  use_batch_norm: true  # 使用批归一化

# 训练配置
training:
  epochs: 100      # 更多训练轮数
  batch_size: 16   # 更大批次（充分利用GPU）
  learning_rate: 0.0005  # 稍低的学习率
  weight_decay: 0.0001
  
  # 优化器配置
  optimizer: "adamw"
  scheduler: "cosine_with_restarts"
  warmup_epochs: 10
  min_lr: 1e-7
  restart_period: 30  # 余弦重启周期
  
  # 混合精度训练
  mixed_precision: true
  gradient_clipping: 0.5
  gradient_accumulation_steps: 2  # 梯度累积
  
  # 早停配置
  early_stopping:
    patience: 15
    min_delta: 0.0005
    monitor: "val_auc"  # 监控AUC而非loss
    restore_best_weights: true

# 数据加载配置
dataloader:
  num_workers: 8   # 更多数据加载进程
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 4  # 更大预取因子
  drop_last: true
  multiprocessing_context: "spawn"  # Windows优化

# 损失函数配置
loss:
  type: "focal"     # Focal Loss处理不平衡
  alpha: 0.25
  gamma: 2.5        # 更强的难样本关注
  label_smoothing: 0.05  # 轻微标签平滑
  class_weights: "balanced"  # 自动平衡类别权重

# 数据增强配置（强增强）
augmentation:
  train:
    horizontal_flip: 0.5
    vertical_flip: 0.2
    rotation: 20
    brightness: 0.3
    contrast: 0.3
    saturation: 0.2
    hue: 0.1
    gaussian_blur: 0.2
    motion_blur: 0.15
    noise: 0.1
    cutout: 0.1
    mixup: 0.2        # Mixup增强
    cutmix: 0.2       # CutMix增强
    normalize: true
    
    # Albumentations增强
    use_albumentations: true
    albumentations_prob: 0.9
    advanced_transforms: true
  
  val:
    normalize: true
    tta: true         # 测试时增强

# 输出配置
output:
  save_dir: "./outputs/high_performance"
  log_dir: "./logs/high_performance"
  checkpoint_dir: "./checkpoints/high_performance"
  save_frequency: 10
  save_best_only: true
  save_top_k: 3     # 保存最好的3个模型
  
# 设备配置
device:
  use_cuda: true
  device_id: 0
  benchmark: true
  deterministic: false
  allow_tf32: true  # 启用TF32加速

# 日志配置
logging:
  level: "INFO"
  log_frequency: 50
  save_predictions: true
  plot_frequency: 5
  tensorboard: true  # 启用TensorBoard
  wandb: false       # 可选：启用Weights & Biases
  
# 评估配置
evaluation:
  metrics: ["accuracy", "auc", "f1", "precision", "recall", "specificity"]
  threshold: 0.5
  save_confusion_matrix: true
  save_roc_curve: true
  save_pr_curve: true
  compute_class_metrics: true
  
# 内存优化
memory:
  cache_size: 2000  # 更大缓存
  clear_cache_frequency: 50
  max_memory_usage: 0.95  # 更高GPU内存使用率
  use_memory_efficient_attention: true
  
# 性能优化
performance:
  compile_model: true  # PyTorch 2.0编译优化
  use_channels_last: true  # 内存布局优化
  fused_optimizer: true    # 融合优化器
  
# 调试配置
debug:
  enabled: false
  max_batches_per_epoch: null
  profile_memory: false
  save_intermediate: false
  detect_anomaly: false
  
# 随机种子
seed: 42

# 恢复训练配置
resume:
  auto_resume: true
  resume_path: null
  reset_optimizer: false
  reset_scheduler: false
  
# 分布式训练配置（为未来扩展准备）
distributed:
  enabled: false
  backend: "nccl"
  find_unused_parameters: false
  
# 模型导出配置
export:
  onnx: true        # 导出ONNX格式
  torchscript: true # 导出TorchScript
  optimize_for_inference: true